# Linux GCC 交叉编译工具链配置
# 用于从 Windows/macOS 交叉编译到 Linux

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# 工具链前缀
set(TOOLCHAIN_PREFIX x86_64-linux-gnu)

# 编译器
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)

# 目标环境路径（根据实际安装位置调整）
if(EXISTS /usr/${TOOLCHAIN_PREFIX})
    set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})
elseif(EXISTS /opt/${TOOLCHAIN_PREFIX})
    set(CMAKE_FIND_ROOT_PATH /opt/${TOOLCHAIN_PREFIX})
endif()

# 搜索行为
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
